#Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  skipDecorator: true

name: 0.6.79-beta$(Rev:.r)

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/test-publishWin

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-sdk-csharp    
    type: dotnet
    to: nuget
    nugetServiceConnection: Nuget.org Take
    dotnetVersion: "3.1.x"
    testProjects: src/Take.Blip.Client.sln
    testPermission: true
